# Generated by Django 5.2.5 on 2025-08-21 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memes',
            options={'ordering': ['upvotes', 'downvotes', 'title']},
        ),
    ]
