# Generated by Django 5.2.5 on 2025-08-21 22:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memes', '0002_alter_memes_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memes',
            options={},
        ),
        migrations.RemoveField(
            model_name='memes',
            name='downvotes',
        ),
        migrations.RemoveField(
            model_name='memes',
            name='upvotes',
        ),
        migrations.CreateModel(
            name='vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='memes.memes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'meme')},
            },
        ),
    ]
