# Generated by Django 5.2.5 on 2025-08-22 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memes', '0003_alter_memes_options_remove_memes_downvotes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='vote_type',
            field=models.CharField(choices=[('UP', 'Upvote'), ('DOWN', 'Downvote')], default='UP', max_length=4),
        ),
    ]
